### ISSUE TITLE
provide internal authentication token

### ISSUE THREAD

**Issue by loomis** [nuvla/api-server#192]
Currently the Nuvla microservices use the password of the 'super' account to authenticate with the main server. This is fragile as changes to this password are not automatically propagated to the microservices. Instead a token-based system should be used. The token would be distributed to the microservices via a "secret". The implementation must allow this token to be updated dynamically while the service is running.

**Comment by 0xbase12** [comment]
why not consider using simple header authentication?

**Comment by schaubl** [comment]
The header auth should work because our microservices target directly the api_server (without going through traefik).

__Edit:__ I tested it and it works but since now user are referenced by UUID, we need to know the UUID of the super user.

Example code using the [python-library](https://github.com/nuvla/python-library).
_Note: the url of Nuvla below works inside a container part of the docker nuvla stack_
```python
from nuvla.api import Api
api = Api('http://api:8200')
api.session.headers['nuvla-authn-info'] = 'user/8d9a6989-25f1-4d4b-9ca7-ec7ddc936edd ADMIN'
```
