### ISSUE TITLE
In tests, detect "index read-only" from ES and halt the execution of the tests

### ISSUE THREAD

**Issue by konstan** [nuvla/api-server#330]
There is no point in continuing with tests if DB puts its indexes into read-only state.

This happens in ES when it sees that it doesn't have enough disk space.

**Comment by 0xbase12** [comment]
@cjdcordeiro got the issue some times ago. 
Now @konstan got the issue when he had 16GB of disk free which is 3% of his full disk space.
To avoid such situation and to not spend a lot of time on fixing this tricky use case I propose the following:
Instead of fixed default percentages of ES settings (85%, 90%, 95%) to determine disk space usage, I'll configure ES to use absolute values fixed to (1gb, 500mb, 100mb)
