### ISSUE TITLE
Propose implementation to allow user swich account or act as a group

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/api-server#341]

**Comment by schaubl** [comment]
I think this can be done with groups. 

The idea is the following: 
* The user can be part of a group. 
* The user can then switch context to the group (like in Exoscale portal).
* By doing this, it will receive and use a new token (session) with the `group-id` as the `user-id` (or better, having a new field `active-claim` so that the `user-id` stay the same and allow to go back to the main user account).
* Then on Nuvla, every part will use `active-claim` instead of `user-id` (ie: when creating an app or a deployment or when adding a subscription, the `active-claim` will be the owner of the resource created).

**Comment by mebster** [comment]
In the case of subscriptions, even if the scope of that subscription might be open to the group (to deploy for example), the ownership of the subscription associated to the `active-claim` must be clear (the `user-id`). So I suspect that the implementation will have to danse between the `active-claim` and the `user-id` depending on the case.
