### ISSUE TITLE
Allow users part of the group nuvla-admin to switch to this group to do admin tasks

### ISSUE THREAD

**Issue by schaubl** [nuvla/api-server#386]
This group will have to behave like other custom group.
UI will have to be updated accordingly.
nuvla-admin group should also be allowed to switch to any other group

**Comment by 0xbase12** [comment]
Some reflection about this change:
Current implementation put always in claims group/nuvla-admin if user is in this group.
-> This can be changed but it make super user also have to switch to group/nuvla-admin to make administrative task.

When user have the group/nuvla-admin in claims, the acl is set to group/nuvla-admin instead of the user. This can also be changed.

A question how to represent the switch group in UI for an active-claim group/nuvla-admin : A big list of all existing users and groups or add an input field to allow admin to manually request it by entering the id? Other proposition are welcome

**Comment by 0xbase12** [comment]
@schaubl @mebster 
Do you agree with proposed changes ?
Do you have a suggestion for the last question ?

**Comment by mebster** [comment]
I think an objective should be that we drop the need for the `super` user. We should only be using personal accounts, some with admin privileges. So having to switch to such group to perform admin tasks makes sense.

**Comment by 0xbase12** [comment]
But we still need a super user to bootstrap and configure Nuvla after a fresh install. How we deal with that?

**Comment by mebster** [comment]
Indeed. We do, but once this is done (bootstrap and initial config), we could decommission the super user or block it?  Or just leave it to operators as good practice (not to use it)?

**Comment by 0xbase12** [comment]
Only allowing a user in group nuvla-admin to switch to group/nuvla-admin to do administrative tasks will be implemented.
Allow group/nuvla-admin to switch to any user or group will be done later #388
