### ISSUE TITLE
Add "published" state for modules

### ISSUE THREAD

**Issue by schaubl** [nuvla/api-server#406]
In the schema and provide a way (an action ?) to set and unset this state for a version of a module.

Top level issue: nuvla/nuvla#39

**Comment by mebster** [comment]
This would allow the creation of the App Store view in the UI and separate apps that are intended for general consumption, from internal apps.

**Comment by 0xbase12** [comment]
**Khaled**
Be able to search module and filter published modules.
A project can’t be published.
Do we need to publish a specific version?
Do we need to publish n versions of the same module?
If yes, this mean we have to do multiple requests to get all published module versions after getting all published modules.
Publish action / Unpublish action or edit is sufficient


**Meb**
Be able to search module and filter published modules? > Yes, therefore there needs to be a “published ” attribute in the module if one of its version is published.
A project can’t be published > Correct
Do we need to publish a specific version? > Yes, only specific version can be published, which allows Clara to work on increments, such that a few versions later, it can be published again.
Do we need to publish n versions of the same module? > several versions can be published
If yes, this mean we have to do multiple requests to get all published module versions after getting all published modules. > We will query modules with an extra  published query attribute to list published modules.  We also need in the versions of the module an extra published attribute (alongside the href, author and commit) to identify the published versions and retrieve the last published version.
Publish action / Unpublish action or edit is sufficient > Since we need to de-normalise the published attribute in the module and the versions list, I suspect a new action is required.  Unless editing this attribute triggered a similar behaviour?

**Decisions**
Add published attribute to versions map. It will allow a search to get all published versions
Publish action on module will publish latest version. On specific version will publish the specific version. Publish action is idempotent.
